# include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
  - "**/*.g.dart"
  - "**/*.gr.dart"
  - "**/*.iconfig.dart"
  - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    public_member_api_docs: false