// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEWqkd4uHE5tpnj1Tg-CzmYoyo8J9cSa4',
    appId: '1:856281683111:android:3140fafae99daead7ef782',
    messagingSenderId: '856281683111',
    projectId: 'alokito-a80e9',
    storageBucket: 'alokito-a80e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv1LWSSAATtD5hTf01e1z8t9OgsQOaaMg',
    appId: '1:856281683111:ios:3cc055d5d6259f077ef782',
    messagingSenderId: '856281683111',
    projectId: 'alokito-a80e9',
    storageBucket: 'alokito-a80e9.appspot.com',
    iosClientId: '856281683111-2funrtrvpmvj565m4ugi81q99omokpgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.alokitoNew',
  );
}
